spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: 27012001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8082
  error:
    include-message: ALWAYS
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  # Timeout Properties
  timelimiter:
    instances:
      inventory:
        timeoutDuration: 3s
  # Retry Properties
  retry:
    instances:
      inventory:
        maxAttempts: 3
        waitDuration: 5s
