spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: 27012001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 0
  error:
    include-message: ALWAYS
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka